[package]
name = "opendrape-render"
description = "OpenDrape offscreen 3D renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
wgpu.workspace = true
glam.workspace = true
bytemuck.workspace = true
image.workspace = true
pollster.workspace = true

[dev-dependencies]
naga.workspace = true

[lints]
workspace = true
