[package]
name = "xtask"
description = "OpenDrape developer tasks"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
image = { workspace = true, features = ["hdr"] }
opendrape-body.workspace = true
glam.workspace = true

[lints]
workspace = true
