//! Generated by `cargo xtask studio` from Poly Haven "Studio Small 08" by Sergej
//! Majboroda (CC0 1.0, https://polyhaven.com/a/studio_small_08), 1k HDR. Do not edit.

/// Irradiance/π as 9 SH coefficients (bands 0 to 2, RGB), white-balanced, key removed.
#[rustfmt::skip]
pub const SH: [[f32; 3]; 9] = [
    [2.295632, 2.295632, 2.295632],
    [-0.549138, -0.542807, -0.531197],
    [0.090506, 0.073534, 0.077408],
    [0.035087, 0.072368, 0.079611],
    [-0.052065, -0.044544, -0.049595],
    [0.024819, 0.020469, 0.024258],
    [0.256657, 0.242751, 0.263971],
    [-0.132569, -0.127552, -0.147488],
    [0.426967, 0.438196, 0.430552],
];

/// Unit vector towards the key light.
#[rustfmt::skip]
pub const KEY_DIR: [f32; 3] = [0.413176, 0.766044, 0.492404];

/// The key light's irradiance/π at normal incidence.
#[rustfmt::skip]
pub const KEY_COLOUR: [f32; 3] = [0.813837, 0.813837, 0.813837];
