//! Generated by `cargo xtask studio` from Poly Haven "Studio Small 08" by Sergej
//! Majboroda (CC0 1.0, https://polyhaven.com/a/studio_small_08), 1k HDR. Do not edit.

/// Irradiance/π as 9 SH coefficients (bands 0 to 2, RGB), white-balanced, key removed.
#[rustfmt::skip]
pub const SH: [[f32; 3]; 9] = [
    [1.950605, 1.950605, 1.950605],
    [-0.431497, -0.425166, -0.413556],
    [-0.354214, -0.371187, -0.367312],
    [-0.338078, -0.300797, -0.293554],
    [-0.085214, -0.077693, -0.082744],
    [-0.014687, -0.019037, -0.015247],
    [0.068765, 0.054858, 0.076079],
    [-0.408059, -0.403042, -0.422977],
    [0.198681, 0.209910, 0.202266],
];

/// Unit vector towards the key light.
#[rustfmt::skip]
pub const KEY_DIR: [f32; 3] = [0.582563, 0.422618, 0.694272];

/// The key light's irradiance/π at normal incidence.
#[rustfmt::skip]
pub const KEY_COLOUR: [f32; 3] = [1.203158, 1.203158, 1.203158];
